ValueError: The image to be converted to a PIL image contains values outside the range [0, 1], got [-1.7890625, 2.140625] which cannot be converted to uint8.