ValueError: The number of images in each batch [0, 0, 0, 0, ...] should be the same  [1] should be the same. Yes, the model does not support having a different number of images per batch.